In [1]:
import numpy as np

In [2]:
A = np.zeros([3, 3, 3], dtype=int)
B = np.ones([3, 3, 3], dtype=int)

In [15]:
print(np.eye(3, k = 1, dtype=int))

[[0 1 0]
 [0 0 1]
 [0 0 0]]


In [22]:
print(np.diag([2,4,6], k=1))

[[0 2 0 0]
 [0 0 4 0]
 [0 0 0 6]
 [0 0 0 0]]


In [26]:
l = [[2,1],[3,4]]
m = np.array(l)
print(l[0][0], m[0,0])

(2, 2)


In [ ]:
def Eulers(v, t, x, h, n):
    for i in range(x, x + h * n, h):
        print(x, t)
        t += h * v(i, t)
    return

In [ ]:
Eulers(5x+3t,0,0,.1,5)