In [9]:
import numpy as np

In [2]:
A = np.zeros([3, 3, 3], dtype=int)
B = np.ones([3, 3, 3], dtype=int)

In [15]:
print(np.eye(3, k = 1, dtype=int))

[[0 1 0]
 [0 0 1]
 [0 0 0]]


In [22]:
print(np.diag([2,4,6], k=1))

[[0 2 0 0]
 [0 0 4 0]
 [0 0 0 6]
 [0 0 0 0]]


In [26]:
l = [[2,1],[3,4]]
m = np.array(l)
print(l[0][0], m[0,0])

(2, 2)


In [15]:
def Eulers(t, x, h, n):
    for i in range(x, x + h * n, h):
        print(x, t)
        t += h * v(i, t)
    return

In [18]:
def v(x,t):
    lol = 4. * t + 5. * x
    return lol

Eulers(0., 0., .1, 5.)

TypeError: range() integer end argument expected, got float.

In [7]:
import numpy as np
cass = [4,3,2,1]
np.array(cass)

array([4, 3, 2, 1])

In [2]:
def squarevector(n):
    return [i ** 2 for i in range(n)]

In [3]:
def squarevectorr(n):
    vec = []
    for i in range(n):
        vec.append(i**2)
    return vec

In [16]:
import numpy as np

def squarearray(n):
    return np.arange(n) ** 2

In [9]:
print(squarevector(5))
print(squarevectorr(5))
print(squarearray(5))

[0, 1, 4, 9, 16]
[0, 1, 4, 9, 16]
[ 0  1  4  9 16]


In [18]:
%timeit squarevector(100000000)
%timeit squarearray(100000000)

1 loop, best of 3: 1min 1s per loop


1 loop, best of 3: 2.98 s per loop


In [14]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [20]:
cass = []
cass.append(5)
print(cass)

[5]


In [22]:
import numpy as np
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]
