In [1]:
#functions for returning true if certain properties

#returns true if even
def even(n):
    if(n%2 == 0):
        return True
    else:
        return False

#returns true if odd
def odd(n):
    if(n%2 != 0):
        return True
    else:
        return False
    
#returns true if prime
def prime(n):
    for i in range(2, n):
        if n%i== 0:
            return False
    return True

print(even(4),even(3),odd(49), odd(54), prime(43), prime(42))

(True, False, True, False, True, False)


In [4]:
#generate a vector containing n numbers of the fibonacci sequence
def fib(n):
    vec = [1,1]
    if n == 1:
        return vec[:1]
    if n == 2:
        return vec[:2]
    for i in range(2,n):
        vec.append(vec[i-1]+vec[i-2])
    return vec

#generate a vector containing the first n squares
def squares(n):
    return [x**2 for x in range(1,n+1)]

print(fib(10))
print(squares(10))

[1, 1, 2, 3, 5, 8, 13, 21, 34, 55]
[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [13]:
# Dot together two vectors with loops
def dot(A, B):
    dot = 0
    if (len(A) != len(B)):
        print("I don't like you. Please pick better lists with same lengths.")
        return
    n = len(A)
    for i in range(n):
        dot += A[i]*B[i]
    return dot

# Dot together two vectors with numpy
import numpy as np
def npdot(A, B):
    return np.dot(A,B)

#check to see they both the same
A = [1, 2, 3]
B = [3, 2, 1]

print(dot(A,B))
print(npdot(A,B))

10
10


In [17]:
#multiply two vectors as matrices using brute force
def mult(A, B):
    rowsA = len(A)
    colsA = len(A[0])
    rowsB = len(B)
    colsB = len(B[0])
    
    if (colsA != rowsB):
        print("I don't like you. Please pick better matrices.")
        return

    prod = [[0 for row in range(colsB)] for col in range(rowsA)]

    for i in range(rowsA):
        for j in range(colsB):
            for k in range(colsA):
                prod[i][j] += A[i][k] * B[k][j]
    return prod

#matrix mult using numpy
import numpy as np

def npmult(A,B):
    return np.matrix(A)*np.matrix(B)

#check to see they both the same
A = [[2,0,0],[1,0,0],[3,0,0]]
B = [[ 1, 2, 3, 4, 5 ], [ 6, 7, 8, 9 , 8 ], [ 7, 6, 5, 4, 3 ]]

print(np.matrix(mult(A,B)))
print(npmult(A,B))

[[ 2  4  6  8 10]
 [ 1  2  3  4  5]
 [ 3  6  9 12 15]]
[[ 2  4  6  8 10]
 [ 1  2  3  4  5]
 [ 3  6  9 12 15]]


In [60]:
#convert spherical to cartesian
from math import sin,cos,pi,sqrt,acos,atan

#input vec in r, theta, phi in degrees 
def spherical2cartesian(vec):
    r = vec[0]
    theta = vec[1]*pi/180
    phi = vec[2]*pi/180
    return [round(r*sin(theta)*cos(phi),3), round(r*sin(theta)*sin(phi),3), round(r*cos(theta),3)]

#input vec in x, y, z
def cartesian2spherical(vec):
    x = vec[0]
    y = vec[1]
    z = vec[2]    
    r = sqrt(x**2 + y**2 + z**2)
    return [round(r,3), round(acos(z/r)*180/pi,1), round(atan(y/x)*180/pi,1)]

#test results
print(spherical2cartesian([3,36,72]))
print(cartesian2spherical([1,1,1]))
print(cartesian2spherical(spherical2cartesian([3,36,72])))

[0.545, 1.677, 2.427]
[1.732, 54.7, 45.0]
[3.0, 36.0, 72.0]


In [ ]:
from visual import sphere
L = 5
R = 0.3
for i in range(-L,L+1):
    for j in range(-L,L+1):
        for k in range(-L,L+1):
            sphere(pos=[i,j,k],radius=R)