In [1]:
#functions for returning true if certain properties

#returns true if even
def even(n):
    if(n%2 == 0):
        return True
    else:
        return False

#returns true if odd
def odd(n):
    if(n%2 != 0):
        return True
    else:
        return False
    
#returns true if prime
def prime(n):
    for i in range(2, n):
        if n%i== 0:
            return False
    return True

print(even(4),even(3),odd(49), odd(54), prime(43), prime(42))

(True, False, True, False, True, False)


In [4]:
#generate a vector containing n numbers of the fibonacci sequence
def fib(n):
    vec = [1,1]
    if n == 1:
        return vec[:1]
    if n == 2:
        return vec[:2]
    for i in range(2,n):
        vec.append(vec[i-1]+vec[i-2])
    return vec

#generate a vector containing the first n squares
def squares(n):
    return [x**2 for x in range(1,n+1)]

print(fib(10))
print(squares(10))

[1, 1, 2, 3, 5, 8, 13, 21, 34, 55]
[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [13]:
# Dot together two vectors with loops
def dot(A, B):
    dot = 0
    if (len(A) != len(B)):
        print("I don't like you. Please pick better lists with same lengths.")
        return
    n = len(A)
    for i in range(n):
        dot += A[i]*B[i]
    return dot

# Dot together two vectors with numpy
import numpy as np
def npdot(A, B):
    return np.dot(A,B)

#check to see they both the same
A = [1, 2, 3]
B = [3, 2, 1]

print(dot(A,B))
print(npdot(A,B))

10
10


In [17]:
#multiply two vectors as matrices using brute force
def mult(A, B):
    rowsA = len(A)
    colsA = len(A[0])
    rowsB = len(B)
    colsB = len(B[0])
    
    if (colsA != rowsB):
        print("I don't like you. Please pick better matrices.")
        return

    prod = [[0 for row in range(colsB)] for col in range(rowsA)]

    for i in range(rowsA):
        for j in range(colsB):
            for k in range(colsA):
                prod[i][j] += A[i][k] * B[k][j]
    return prod

#matrix mult using numpy
import numpy as np

def npmult(A,B):
    return np.matrix(A)*np.matrix(B)

#check to see they both the same
A = [[2,0,0],[1,0,0],[3,0,0]]
B = [[ 1, 2, 3, 4, 5 ], [ 6, 7, 8, 9 , 8 ], [ 7, 6, 5, 4, 3 ]]

print(np.matrix(mult(A,B)))
print(npmult(A,B))

[[ 2  4  6  8 10]
 [ 1  2  3  4  5]
 [ 3  6  9 12 15]]
[[ 2  4  6  8 10]
 [ 1  2  3  4  5]
 [ 3  6  9 12 15]]


In [60]:
#convert spherical to cartesian
from math import sin,cos,pi,sqrt,acos,atan

#input vec in r, theta, phi in degrees 
def spherical2cartesian(vec):
    r = vec[0]
    theta = vec[1]*pi/180
    phi = vec[2]*pi/180
    return [round(r*sin(theta)*cos(phi),3), round(r*sin(theta)*sin(phi),3), round(r*cos(theta),3)]

#input vec in x, y, z
def cartesian2spherical(vec):
    x = vec[0]
    y = vec[1]
    z = vec[2]    
    r = sqrt(x**2 + y**2 + z**2)
    return [round(r,3), round(acos(z/r)*180/pi,1), round(atan(y/x)*180/pi,1)]

#test results
print(spherical2cartesian([3,36,72]))
print(cartesian2spherical([1,1,1]))
print(cartesian2spherical(spherical2cartesian([3,36,72])))

[0.545, 1.677, 2.427]
[1.732, 54.7, 45.0]
[3.0, 36.0, 72.0]


In [ ]:
# What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?
# First implementation is original and a lot slower. Second one is faster.

In [55]:
from math import log

# function that checks if x is prime
def prime(x):
    for n in range(2, x):
        if x%n == 0:
            return False
    return True

# Initial attempt (a bit of smart brute forcing) 
def challenge_solution(n):
    #sort out nonfactors and primes
    nonfactors = []
    primes = []
    for i in range(2,n):
        if (n%i != 0):
            nonfactors.append(i)
        if prime(i):
            primes.append(i)

    #since 'nonfactors' is the list we check if it's a factor,
    #we must account for 'n' as well as nonfactors, so we append this to the end       
    nonfactors.append(n)

    #minimum incrementing factor is the product of all primes
    minimum = 2
    for i in range(1,len(primes)):
        minimum*=primes[i]

    #time to do the bruteforcing! now with a massive incrementing value though!
    bool = True
    x = minimum
    while bool:
        x+=minimum
        for i in range(len(nonfactors)):
            if (x%nonfactors[i] != 0):
                break
            if (i == len(nonfactors)-1 and bool):
                bool = False
    return x

# Main function for the method that calculates LCM based on the orders of primes
def challenge_solution_fast(n):
    x = 2**int(log(n,2))
    for i in range(3,n,2):
        if prime(i):
            x *= i**int(log(n,i))
    return x


# Main function for the method that calculates LCM based on the orders of primes
# Using prime sieve courtesy of Robert William Hanks (RWH1)
# http://stackoverflow.com/questions/2068372/fastest-way-to-list-all-primes-below-n-in-python/3035188#3035188
def challenge_solution_RWH(n):
    sieve = [True] * ((n+1)/2)
    for i in range(3,int((n+1)**0.5)+1,2):
        if sieve[i/2]:
            sieve[i*i/2::i] = [False] * ((n-i*i-1)/(2*i)+1)
    x = 2**int(log((n+1),2))
    for i in range(1,n/2):
        if sieve[i]:
            x *= (2*i+1)**int(log((n+1),2*i+1))
    return x


n = 50
# %timeit challenge_solution(n)
%timeit challenge_solution_fast(n)
%timeit challenge_solution_RWH(n)
print(challenge_solution_fast(n))
print(challenge_solution_RWH(n))

The slowest run took 12.18 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 3: 69.5 µs per loop


10000 loops, best of 3: 19.7 µs per loop
3099044504245996706400
3099044504245996706400


In [56]:
# Euler's method in two ways: with numpy and without

import numpy as np

# define the initial conditions here
t0 = 0
x0 = 1
h = .01
N = 100
def v(x,t):
    return -3*x

# do the euler's without numpy
def euler_python(t0,x0, v, h, N):
    solution_python = [[t0],[x0]]
    for i in range(1,N+1):
        prevT = solution_python[0][i-1]
        prevX = solution_python[1][i-1]
        solution_python[0].append(round(prevT+h,5))
        solution_python[1].append(round(prevX+h*v(prevX,prevT),5))
    return solution_python

# do the euler's with numpy
def euler_numpy(t0,x0, v, h, N):
    times = np.arange(t0,t0+h*N+h, h)
    position = np.zeros(len(times))
    position[0] = x0
    for i in range(1,len(times)):
        position[i] = position[i-1] + v(position[i-1],times[i-1])*h
    solution_numpy = np.array([times,position])
    return solution_numpy

%timeit euler_python(t0,x0,v,h,N)
%timeit euler_numpy(t0,x0,v,h,N)

#print numerical solution
solution = euler_numpy(t0,x0,v,h,N)
print(solution)

#import matplotlib to plot numerical and exact solution
import matplotlib.pyplot as plt

#plot numerical solution
plt.plot(solution[0],solution[1],color='r')
#plot exact solution for v = -3x
x = np.linspace(t0,N*h,100)
y = np.exp(-3*x)
plt.plot(x,y,color='g')

plt.show()

1000 loops, best of 3: 276 µs per loop


The slowest run took 5.51 times longer than the fastest. This could mean that an intermediate result is being cached.
1000 loops, best of 3: 346 µs per loop
[[ 0.          0.01        0.02        0.03        0.04        0.05        0.06
   0.07        0.08        0.09        0.1         0.11        0.12        0.13
   0.14        0.15        0.16        0.17        0.18        0.19        0.2
   0.21        0.22        0.23        0.24        0.25        0.26        0.27
   0.28        0.29        0.3         0.31        0.32        0.33        0.34
   0.35        0.36        0.37        0.38        0.39        0.4         0.41
   0.42        0.43        0.44        0.45        0.46        0.47        0.48
   0.49        0.5         0.51        0.52        0.53        0.54        0.55
   0.56        0.57        0.58        0.59        0.6         0.61        0.62
   0.63        0.64        0.65        0.66        0.67        0.68        0.69
   0.7         0.71        0.72        0.73 